# Generated by Django 5.0.7 on 2024-07-31 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahim', '0002_madrasadetails_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zakatdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zakat_date', models.DateField()),
                ('zakat_amount', models.IntegerField(null=True)),
                ('slip_no', models.IntegerField(null=True)),
                ('madrasa_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fahim.madrasadetails')),
            ],
        ),
    ]
