# Generated by Django 5.0.7 on 2024-08-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahim', '0003_zakatdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakatdetails',
            name='madrasa_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='fahim.madrasadetails'),
        ),
    ]
