# Generated by Django 5.0.7 on 2024-08-04 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fahim', '0004_alter_zakatdetails_madrasa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakatdetails',
            name='madrasa_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='madrasa', to='fahim.madrasadetails'),
        ),
    ]
